CREATE PROC SP_CHUYENLOP
@MASV NCHAR(10), @MALOP NCHAR(10)
AS
BEGIN
	SET XACT_ABORT ON
	BEGIN DISTRIBUTED TRANSACTION -- bắt đầu giao tác phân tán
	
	IF EXISTS(SELECT MASV FROM dbo.SINHVIEN WHERE MASV=@MASV)
	BEGIN
		IF NOT EXISTS(SELECT MALOP FROM dbo.LOP WHERE MALOP=@MALOP)
		BEGIN
			IF EXISTS(SELECT MALOP FROM LINK0.QLSVTC.dbo.LOP WHERE MALOP=@MALOP)
				RAISERROR( 'Không tìm thấy mã lớp tương ứng.', 16, 1);
		END
		ELSE
			BEGIN TRY
				-- 
				INSERT INTO LINK0.QLSVTC.dbo.SINH
			END TRY
			BEGIN CATCH
				SELECT
					ERROR_MESSAGE() AS ErrorMessage,
					ERROR_NUMBER() AS ErrorNumber,
					ERROR_LINE() AS ErrorLine;
			END CATCH;
		END
	END
	ELSE
		RAISERROR( 'Không tìm thấy mã sinh viên.', 16, 1);
		RETURN;
	END
