USE [QLSVTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_REPORT_IN_DSSV_2]    Script Date: 12/2/2024 10:18:11 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_REPORT_IN_DSSV_2]
	@MALOP NVARCHAR(10)
AS
BEGIN
	IF EXISTS(SELECT 1 FROM dbo.LOP WHERE MALOP = @MALOP)
		SELECT * FROM dbo.SINHVIEN sv WHERE sv.MALOP = @MALOP
	ELSE
	BEGIN
		IF EXISTS(SELECT 1 FROM LINK0.QLSVTC.dbo.LOP WHERE MALOP = @MALOP)
			SELECT * FROM LINK0.QLSVTC.dbo.SINHVIEN sv WHERE sv.MALOP = @MALOP
		ELSE
			RAISERROR(N'Mã lớp không tồn tại!', 16, 1)
	END
END
GO

