USE [QLSVTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_SV_DANGKY]    Script Date: 12/11/2024 5:46:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_SV_DANGKY]
	@MASV NCHAR(10),
	@MALTC NCHAR(10),
	@namhoc INT,
	@hk INT
AS 
DECLARE @TB_LTC TABLE (MATB INT)
DECLARE @TB_NK TABLE (MATB INT)
SET XACT_ABORT ON;
BEGIN
	BEGIN TRY
		INSERT INTO @TB_LTC (MATB)  --lớp tín chỉ
		SELECT MATB FROM GIANGDAY g WHERE g.MALTC = @MALTC

		IF OBJECT_ID('tempdb..##ltc_mo_dk') IS NOT NULL
			DROP TABLE #ltc_mo_dk;

			CREATE TABLE #ltc_mo_dk(
				MALTC INT,
				MAMH NCHAR(10),
				TENMH NVARCHAR(50),
				NHOM INT,
				HOTEN NVARCHAR(MAX),
				DADANGKY INT
			);
			INSERT INTO #ltc_mo_dk (MALTC, MAMH, TENMH, NHOM, HOTEN, DADANGKY)
			EXEC SP_HT_DANGKY @NAMHOC = @namhoc, @HK = @hk;

			INSERT INTO @TB_NK (MATB) -- niên khóa
			SELECT MATB FROM GIANGDAY g WHERE g.MALTC IN 
			(SELECT L.MALTC 
			FROM (SELECT MALTC FROM DANGKY WHERE MASV=@MASV) AS D
			INNER JOIN #ltc_mo_dk L ON D.MALTC = L.MALTC
			)

			IF NOT EXISTS( SELECT 1 FROM @TB_LTC x WHERE x.MATB IN (SELECT y.MATB FROM @TB_NK y))
				BEGIN
					INSERT INTO DANGKY(MALTC, MASV) VALUES (@MALTC, @MASV) -- dangky
					PRINT N'Đăng ký lớp tín chỉ thành công!'
				END
			ELSE
				RAISERROR(N'Trùng lịch học',16, 1)
		END TRY
		BEGIN CATCH
			PRINT N'Đã xảy ra lỗi: ' + ERROR_MESSAGE();
		END CATCH
		DELETE FROM #ltc_mo_dk;
		INSERT INTO #ltc_mo_dk (MALTC, MAMH, TENMH, NHOM, HOTEN, DADANGKY)
		EXEC SP_HT_DANGKY @NAMHOC = @namhoc, @HK = @hk;
		SELECT * FROM #ltc_mo_dk
END
GO

